name: NodeJS with Webpack

on:
  push:
    branches: [ "interview-base-code" ]
  pull_request:
    branches: [ "interview-base-code" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install
      run: npm i

    - name: Build
      run: |
        webpack --mode production

    - name: Deploy to GH Page
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: dist
